
source:      .
destination: ./_site
plugins:     ./_plugin
layouts:     ./_layout
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git']
gems:        []
timezone:    nil
encoding:    UTF-8

future:      true
show_drafts: nil
limit_posts: 0
pygments:    true

relative_permalinks: true

permalink:   date
paginate_path: 'page:num'

markdown:    kramdown
markdown_ext: markdown,mkd,mkdn,md
textile_ext: textile

excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: false,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

title: Fehérke's Github Site
lang: en
style:
  - /style.css
meta:
  author: Fehérke
#  copyright: copyright (c) 2012, Fehérke
icon: /favicon.ico
layout: page
github: http://github.com/feherke
extension: .md
filetype:
  ahk: script
  awk: script
  css: css
  conf: config
  html: html
  ini: config
  js: script
  md: markdown
  php: embed
  pl: script
  pm: script
  pod: pod
  rb: script
  sdf: binary
  sh: script
#  svg: xml # NOT READY YET
  svg: html
  ttf: binary
  txt: text
  woff: binary
  xml: html # NOT READY YET
#  xpm: image # NOT READY YET
  "1": man
  "6": man
status:
  stable: As far as I know it is functional.
  unstable: Has known bugs, but can be used.
  outdated: Once stable, now needs update to be stable again.
  buggy: Not to be used.
  active: Developed occasionally and tested regularly.
  inactive: Neither developed or tested regularly, but I keep an eye on it.
  dormant: Currently not developed or tested, but planned to resurrect it.
  abandoned: No current nor future development or testing planned.
